### ISSUE TITLE
Wrap HM CMB with if( ! class_exists( 'CMB_Field' ) ) 

### ISSUE THREAD

**Issue by mwtsn** [mkdo/kapow-theme#1]
Wrap HM CMB with if( ! class_exists( 'CMB_Field' ) ) 
so if it has been included elsewhere it doesnt get included again

**Comment by mwtsn** [comment]
Hey @davetgreen I'll take this one if its ok, It doesn't include the CSS and JS correctly if included direct in a theme such as this, I'm currently working a solution out for this on Posium, so I'll implement it when its ready.

**Comment by davetgreen** [comment]
@mwtsn yeah cool! there's a long discussion about it on the CMB repo actually. Needs a hack to work around it. Last could of builds I've gone down the mu-plugins route so I guess that's the way forward now.

**Comment by mwtsn** [comment]
In that case @davetgreen I'm going to request that rather then add this into the theme, the Kapow Composer element simply adds it to MU folder.

I'll deal with Posium as a special case, and do the workaround (should be simple enough to hack).

**Comment by davetgreen** [comment]
Closing @mwtsn as we've got the Composer set-up now.
