### ISSUE TITLE
retina image issue

### ISSUE THREAD

**Issue by nervewax** [mkdo/kapow-theme#8]
On this site
https://dbhweb.wpengine.com/

The retina version of the image is not loading because
```
Mixed Content:
The page at 'https://dbhweb.wpengine.com/' was loaded over HTTPS,
but requested an insecure image 'http://dbhweb.wpengine.com/wp-content/uploads/2017/05/dbh-logox2.png'. 
This request has been blocked; the content must be served over HTTPS.
```

**Comment by davetgreen** [comment]
@nervewax This is the code for the logo, right? There's nothing in the header code that makes me think that the theme is at fault, leaning towards this being a more data/server oddity?

**Comment by davetgreen** [comment]
Closing as this has been demonstrated to be a server/protocol/data issue.
